name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Remove existing repo (if any)
          rm -rf ~/GolfDashboard

          # Clone fresh copy
          git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git ~/GolfDashboard
          
          # Go into project dir
          cd ~/GolfDashboard

          # Install deps & restart app (adjust as needed)
          nohup npm install && npm run dev > out.log 2>&1 & disown
          exit
        EOF
